"""empty message

Revision ID: 035f96a40234
Revises: fa6d160af899
Create Date: 2025-10-06 23:55:26.439174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f96a40234'
down_revision = 'fa6d160af899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bombshells')
    with op.batch_alter_table('islander', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bombshell', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islander', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('bombshell')

    op.create_table('bombshells',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hometown', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bombshells_pkey')
    )
    # ### end Alembic commands ###
