"""empty message

Revision ID: 2f143aac6cc1
Revises: 8bdf04b3d416
Create Date: 2025-10-04 01:24:56.103004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f143aac6cc1'
down_revision = '8bdf04b3d416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=70), nullable=False))
        batch_op.add_column(sa.Column('phonenumber', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=260), nullable=True))
        batch_op.create_unique_constraint(None, ['phonenumber'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('phonenumber')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
