"""Initial migration

Revision ID: 4a78e28026bf
Revises: 
Create Date: 2025-11-04 00:51:52.085566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a78e28026bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('islander',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('bombshell', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.String(length=260), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('username', sa.String(length=70), nullable=False),
    sa.Column('phonenumber', sa.Integer(), nullable=True),
    sa.Column('profile_image', sa.String(length=260), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phonenumber'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorite_islanders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('islander_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['islander_id'], ['islander.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'islander_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_islanders')
    op.drop_table('user')
    op.drop_table('islander')
    # ### end Alembic commands ###
