"""empty message

Revision ID: 75c3ec1861a8
Revises: ce3ad868b09d
Create Date: 2025-10-31 23:36:49.354041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c3ec1861a8'
down_revision = 'ce3ad868b09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islander', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=260), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('islander', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
