"""empty message

Revision ID: bb5a121c0300
Revises: 2f143aac6cc1
Create Date: 2025-10-07 00:33:41.194572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5a121c0300'
down_revision = '2f143aac6cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('islander',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('bombshell', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_islanders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('islander_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['islander_id'], ['islander.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'islander_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_islanders')
    op.drop_table('islander')
    # ### end Alembic commands ###
